[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
verification_policy_noop = "5gPMypQiHYVmx3jFJAGr72wrB7f1bgmud3mHtpHUGyLd"

[programs.localnet]
verification_policy_noop = "5gPMypQiHYVmx3jFJAGr72wrB7f1bgmud3mHtpHUGyLd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'No Anchor tests — pure solana-program. Use cargo test-sbf.'"
